import { SummaryResponse, ChatMessage } from '../types/index.js';
import { NOT_FOUND_TEXT } from '../constants/index.js';

export function exportSummaryToMarkdown(summary: SummaryResponse, followUps: ChatMessage[] = []): string {
  const { source, summary: overview, keyPoints, actions, numbersMetrics, decisions, risks, warnings } = summary;

  let md = `# ${source.title || 'Untitled Page'}\n\n`;
  md += `**Source URL:** ${source.url}\n`;
  md += `**Captured At:** ${new Date(source.capturedAt).toLocaleString()}\n`;
  md += `**Capture Mode:** ${source.captureMode.toUpperCase()}\n`;
  md += `**Language:** ${source.language || 'en'}\n`;
  md += `**Word Count:** ${source.wordCount}\n\n`;

  if (warnings && warnings.length > 0) {
    md += `> **Warnings:** ${warnings.join('; ')}\n\n`;
  }

  md += `---\n\n`;

  // 1. Summary
  md += `## 1. Summary\n\n`;
  md += `${overview.line1}\n\n`;
  md += `${overview.line2}\n\n`;

  // 2. Key Points
  md += `## 2. Key Points\n\n`;
  if (keyPoints.length === 0 || (keyPoints.length === 1 && keyPoints[0].text === NOT_FOUND_TEXT)) {
    md += `${NOT_FOUND_TEXT}\n\n`;
  } else {
    keyPoints.forEach((kp) => {
      md += `- ${kp.text} _(Confidence: ${kp.confidence})_\n`;
    });
    md += `\n`;
  }

  // 3. Actions
  md += `## 3. Actions\n\n`;
  if (actions.length === 0 || (actions.length === 1 && actions[0].text === NOT_FOUND_TEXT)) {
    md += `${NOT_FOUND_TEXT}\n\n`;
  } else {
    actions.forEach((act) => {
      const owner = act.owner ? ` [Owner: ${act.owner}]` : '';
      const due = act.dueDate ? ` [Due: ${act.dueDate}]` : '';
      md += `- ${act.text}${owner}${due} _(Confidence: ${act.confidence})_\n`;
    });
    md += `\n`;
  }

  // 4. Numbers & Metrics
  md += `## 4. Numbers & Metrics\n\n`;
  if (numbersMetrics.length === 0 || (numbersMetrics.length === 1 && numbersMetrics[0].label === NOT_FOUND_TEXT)) {
    md += `${NOT_FOUND_TEXT}\n\n`;
  } else {
    numbersMetrics.forEach((nm) => {
      const ctx = nm.context ? ` (${nm.context})` : '';
      md += `- **${nm.label}:** ${nm.value}${ctx} _(Confidence: ${nm.confidence})_\n`;
    });
    md += `\n`;
  }

  // 5. Decisions
  md += `## 5. Decisions\n\n`;
  if (decisions.length === 0 || (decisions.length === 1 && decisions[0].text === NOT_FOUND_TEXT)) {
    md += `${NOT_FOUND_TEXT}\n\n`;
  } else {
    decisions.forEach((dec) => {
      md += `- ${dec.text} _(Confidence: ${dec.confidence})_\n`;
    });
    md += `\n`;
  }

  // 6. Risks
  md += `## 6. Risks\n\n`;
  if (risks.length === 0 || (risks.length === 1 && risks[0].text === NOT_FOUND_TEXT)) {
    md += `${NOT_FOUND_TEXT}\n\n`;
  } else {
    risks.forEach((r) => {
      md += `- [Severity: ${r.severity.toUpperCase()}] ${r.text} _(Confidence: ${r.confidence})_\n`;
    });
    md += `\n`;
  }

  // Follow-up Q&A section if present
  if (followUps.length > 0) {
    md += `---\n\n## Follow-up Questions & Answers\n\n`;
    followUps.forEach((msg) => {
      if (msg.sender === 'user') {
        md += `**Q:** ${msg.text}\n\n`;
      } else {
        md += `**A:** ${msg.text}\n\n`;
      }
    });
  }

  md += `---\n_Generated by Lumen — On-screen Intelligence_\n`;
  return md;
}

export function exportSummaryToPlainText(summary: SummaryResponse): string {
  const { source, summary: overview, keyPoints, actions, numbersMetrics, decisions, risks } = summary;
  let text = `LUMEN BRIEF: ${source.title || 'Untitled Page'}\nURL: ${source.url}\n\n`;
  text += `1. SUMMARY\n${overview.line1}\n${overview.line2}\n\n`;

  text += `2. KEY POINTS\n`;
  text += keyPoints.map((k) => `* ${k.text}`).join('\n') || NOT_FOUND_TEXT;
  text += `\n\n3. ACTIONS\n`;
  text += actions.map((a) => `* ${a.text}`).join('\n') || NOT_FOUND_TEXT;
  text += `\n\n4. NUMBERS & METRICS\n`;
  text += numbersMetrics.map((n) => `* ${n.label}: ${n.value}`).join('\n') || NOT_FOUND_TEXT;
  text += `\n\n5. DECISIONS\n`;
  text += decisions.map((d) => `* ${d.text}`).join('\n') || NOT_FOUND_TEXT;
  text += `\n\n6. RISKS\n`;
  text += risks.map((r) => `* [${r.severity}] ${r.text}`).join('\n') || NOT_FOUND_TEXT;

  return text;
}
